# Generated by Django 6.1.1 on 2026-09-26 12:32

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_prato', models.CharField(max_length=100)),
                ('ingredientes', models.TextField()),
                ('modo_preparo', models.CharField()),
                ('tempo_preparo', models.IntegerField()),
                ('rendimento', models.CharField(max_length=10)),
                ('categoria', models.CharField(max_length=100)),
                ('date_prato', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('publicado', models.BooleanField(default=False)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
